name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@clang-format-19
      with:
        itk-branch: master
        error-message: "Remote module code is inconsistent with ITK Coding Style (20241205)."
